on:
  - push

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Lint
        run: |
          yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Test with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest
          package-manager: yarn
